// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKvNTpB19GyEeL8PHsei5Bz1w7Vv8sPgk',
    appId: '1:1022234921629:web:623577557974cfad1de274',
    messagingSenderId: '1022234921629',
    projectId: 'childguard-3051f',
    authDomain: 'childguard-3051f.firebaseapp.com',
    storageBucket: 'childguard-3051f.firebasestorage.app',
    measurementId: 'G-BVKFKPCKVR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxg6q3TgeExErCbUtmgVwguBXVuZLvEmU',
    appId: '1:1022234921629:android:ac7a1966ae2f7ae41de274',
    messagingSenderId: '1022234921629',
    projectId: 'childguard-3051f',
    storageBucket: 'childguard-3051f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA4ZG3D5R7FPc4Lvgt7irPwEmg0iUEHkc',
    appId: '1:1022234921629:ios:bea3f7f23ed098391de274',
    messagingSenderId: '1022234921629',
    projectId: 'childguard-3051f',
    storageBucket: 'childguard-3051f.firebasestorage.app',
    iosBundleId: 'y',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBA4ZG3D5R7FPc4Lvgt7irPwEmg0iUEHkc',
    appId: '1:1022234921629:ios:bea3f7f23ed098391de274',
    messagingSenderId: '1022234921629',
    projectId: 'childguard-3051f',
    storageBucket: 'childguard-3051f.firebasestorage.app',
    iosBundleId: 'y',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKvNTpB19GyEeL8PHsei5Bz1w7Vv8sPgk',
    appId: '1:1022234921629:web:6387da9b4310e5971de274',
    messagingSenderId: '1022234921629',
    projectId: 'childguard-3051f',
    authDomain: 'childguard-3051f.firebaseapp.com',
    storageBucket: 'childguard-3051f.firebasestorage.app',
    measurementId: 'G-KERQ3VPL5F',
  );
}
